# Generated by Django 4.1.4 on 2023-01-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground_app", "0007_alter_playground_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playground",
            name="location",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="playground",
            name="created_at",
            field=models.CharField(
                default="02 Jan, 2023 - 12h35m39 AM", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="playground",
            name="updated_at",
            field=models.CharField(
                default="02 Jan, 2023 - 12h35m39 AM", max_length=100
            ),
        ),
    ]
