# Generated by Django 4.1.4 on 2023-02-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "playground_app",
            "0008_playground_location_alter_playground_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="playground",
            name="created_at",
            field=models.CharField(
                default="16 Feb, 2023 - 07h04m39 AM", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="playground",
            name="updated_at",
            field=models.CharField(
                default="16 Feb, 2023 - 07h04m39 AM", max_length=100
            ),
        ),
    ]
