# Generated by Django 4.1.4 on 2023-06-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground_app', '0009_alter_playground_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='created_at',
            field=models.CharField(default='25 Jun, 2023 - 05h18m02 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='playground',
            name='updated_at',
            field=models.CharField(default='25 Jun, 2023 - 05h18m02 PM', max_length=100),
        ),
    ]
